behaviors:
  AIPlayer:
    trainer_type: ppo
    max_steps: 5_000_000
    summary_freq: 10000
    checkpoint_interval: 10000
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      num_epoch: 5
      epsilon: 0.2
      #beta: 0.01
    network_settings:
      hidden_units: 256
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
      gail:
        strength: 0.5
        demo_path:  
    behavioral_cloning:
      strength: 0.5
      demo_path: